[package]
name = "rustyknife-console"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
rustyknife-z = { path = "../rustyknife-z" }
structopt = "0.2.14"
rand = "0.8.5"
