[package]
name = "rustyknife"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
quick-error = "1.2.2"
rand = "0.6.3"
rand_pcg = "0.1.1"

[dev-dependencies]
difference = "2.0.0"
