[package]
name = "rustyknife-irc"
version = "0.1.0"
authors = ["Thomas ten Cate <ttencate@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.1.25"
irc = "0.13.6"
rustyknife = { path = "../rustyknife" }
structopt = "0.2.14"
